#!/usr/bin/env python3
"""Measure FlyBody aerodynamic support with exact measured wing kinematics.

This diagnostic deliberately bypasses wing actuators, motor neurons, virtual muscles,
and wing inertial tracking.  At each phase of the official measured wingbeat it writes
wing qpos/qvel directly into two otherwise-identical compiled FlyBody models: one with
the restored wing ellipsoid-fluid geoms and one without them.  After ``mj_forward`` it
compares the free-root vertical generalized passive force.

The difference isolates the vertical support generated by the restored wing fluid
geometries at the *exact* requested kinematics.  Therefore:

* support_ratio ~= 1: the aerodynamic geometry/unit port can support body weight and
  the remaining failure is upstream in wing dynamics/actuation/tracking;
* support_ratio << 1: even exact wing kinematics underproduce lift, pointing to fluid
  geometry/frame/global-unit semantics rather than the controller.

This is a calibration-only diagnostic and does not alter the training path.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import mujoco as mj
import numpy as np

from flybody_adapter import FlyBodyWingAdapter
from flybody_biophysics import normalize_fly_mass
from flybody_measured_wingbeat import AXES, DEFAULT_PATTERN, MeasuredWingbeatCycle


PUBLISHED_FLYBODY_MASS_MG = 0.983
SOURCE_GRAVITY_MM_S2 = 9810.0
LEG_PREFIXES = ("lf_", "lm_", "lh_", "rf_", "rm_", "rh_")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pattern", type=Path, default=DEFAULT_PATTERN)
    parser.add_argument("--phase-samples", type=int, default=1000)
    parser.add_argument(
        "--root-pitches-deg",
        type=float,
        nargs="+",
        default=(0.0, 47.5),
    )
    parser.add_argument(
        "--leg-poses",
        nargs="+",
        choices=("neutral", "source_retracted"),
        default=("neutral", "source_retracted"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("artifacts/embodiment/flybody-kinematic-aero-support.json"),
    )
    return parser.parse_args()


def make_body(*, aerodynamics: bool, root_pitch_deg: float) -> FlyBodyWingAdapter:
    body = FlyBodyWingAdapter(
        tethered=False,
        spawn_position_mm=(0.0, 0.0, 8.25),
        flight_body_pitch_deg=float(root_pitch_deg),
        initial_linear_velocity_mm_s=(0.0, 0.0, 0.0),
        enable_vision=False,
        enable_wing_aerodynamics=aerodynamics,
        normalize_canonical_mass=False,
    )
    normalize_fly_mass(
        body.sim,
        body.fly,
        target_mass_g=PUBLISHED_FLYBODY_MASS_MG / 1000.0,
    )
    return body


def leg_springrefs(body) -> list[tuple[int, int, float]]:
    result: list[tuple[int, int, float]] = []
    for dof in body._all_dofs:
        if not str(dof.child.name).startswith(LEG_PREFIXES):
            continue
        qpos_address, qvel_address = body._joint_state_addresses(dof)
        result.append(
            (
                qpos_address,
                qvel_address,
                float(body.sim.mj_model.qpos_spring[qpos_address]),
            )
        )
    if len(result) != 66:
        raise RuntimeError(f"expected 66 leg DoFs, found {len(result)}")
    return result


def enforce_leg_pose(body, pose: str, refs: list[tuple[int, int, float]]) -> None:
    if pose == "neutral":
        return
    if pose != "source_retracted":
        raise KeyError(pose)
    for qpos_address, qvel_address, springref in refs:
        body.sim.mj_data.qpos[qpos_address] = springref
        body.sim.mj_data.qvel[qvel_address] = 0.0


def root_state(body) -> tuple[np.ndarray, int, int]:
    qpos_address = body._root_freejoint_qpos_address()
    qvel_address = body._root_freejoint_dof_address()
    return (
        np.asarray(
            body.sim.mj_data.qpos[qpos_address : qpos_address + 7],
            dtype=np.float64,
        ).copy(),
        qpos_address,
        qvel_address,
    )


def set_exact_state(
    body,
    cycle: MeasuredWingbeatCycle,
    phase: float,
    *,
    root_qpos: np.ndarray,
    root_qpos_address: int,
    root_qvel_address: int,
    leg_pose: str,
    leg_refs: list[tuple[int, int, float]],
) -> None:
    body.sim.mj_data.qpos[root_qpos_address : root_qpos_address + 7] = root_qpos
    body.sim.mj_data.qvel[root_qvel_address : root_qvel_address + 6] = 0.0
    enforce_leg_pose(body, leg_pose, leg_refs)

    angles = cycle.angles(phase, 1.0)
    velocities = cycle.velocities(phase, 1.0, body.wingbeat_hz)
    for side in ("left", "right"):
        for axis in AXES:
            actuator_index = body._wing_indices[(side, axis)]
            dof = body._actuated_dofs[actuator_index]
            qpos_address, qvel_address = body._wing_state_addresses(dof)
            body.sim.mj_data.qpos[qpos_address] = angles[axis]
            body.sim.mj_data.qvel[qvel_address] = velocities[axis]

    # Controls are irrelevant because no integration is performed; keep them neutral
    # so actuator state cannot contaminate the passive-force comparison.
    body.sim.mj_data.ctrl[:] = 0.0
    body.sim.mj_data.qfrc_applied[:] = 0.0
    mj.mj_forward(body.sim.mj_model, body.sim.mj_data)


def fly_mass_g(body) -> float:
    ids: list[int] = []
    for segment in body.fly.get_bodysegs_order():
        name = body.fly.bodyseg_to_mjcfbody[segment].name
        body_id = mj.mj_name2id(body.sim.mj_model, mj.mjtObj.mjOBJ_BODY, name)
        if body_id <= 0:
            raise RuntimeError(f"compiled FlyBody body not found: {name}")
        ids.append(body_id)
    return float(np.sum(np.asarray(body.sim.mj_model.body_mass)[sorted(set(ids))]))


def run_case(
    cycle: MeasuredWingbeatCycle,
    *,
    root_pitch_deg: float,
    leg_pose: str,
    phase_samples: int,
) -> dict[str, object]:
    off = make_body(aerodynamics=False, root_pitch_deg=root_pitch_deg)
    on = make_body(aerodynamics=True, root_pitch_deg=root_pitch_deg)

    off_leg_refs = leg_springrefs(off)
    on_leg_refs = leg_springrefs(on)
    off_root, off_qpos, off_qvel = root_state(off)
    on_root, on_qpos, on_qvel = root_state(on)

    mass_off = fly_mass_g(off)
    mass_on = fly_mass_g(on)
    if not math.isclose(mass_off, mass_on, rel_tol=1e-9, abs_tol=1e-12):
        raise RuntimeError(f"aero A/B mass mismatch: off={mass_off} on={mass_on}")

    vertical_forces: list[float] = []
    off_passive: list[float] = []
    on_passive: list[float] = []
    for index in range(phase_samples):
        phase = 2.0 * math.pi * index / phase_samples
        set_exact_state(
            off,
            cycle,
            phase,
            root_qpos=off_root,
            root_qpos_address=off_qpos,
            root_qvel_address=off_qvel,
            leg_pose=leg_pose,
            leg_refs=off_leg_refs,
        )
        set_exact_state(
            on,
            cycle,
            phase,
            root_qpos=on_root,
            root_qpos_address=on_qpos,
            root_qvel_address=on_qvel,
            leg_pose=leg_pose,
            leg_refs=on_leg_refs,
        )

        off_z = float(off.sim.mj_data.qfrc_passive[off_qvel + 2])
        on_z = float(on.sim.mj_data.qfrc_passive[on_qvel + 2])
        off_passive.append(off_z)
        on_passive.append(on_z)
        vertical_forces.append(on_z - off_z)

    force = np.asarray(vertical_forces, dtype=np.float64)
    support_accel = force / mass_on
    mean_support = float(np.mean(support_accel))
    return {
        "root_pitch_deg": float(root_pitch_deg),
        "leg_pose": leg_pose,
        "phase_samples": int(phase_samples),
        "body_mass_mg": mass_on * 1000.0,
        "mean_added_vertical_force_g_mm_s2": float(np.mean(force)),
        "std_added_vertical_force_g_mm_s2": float(np.std(force)),
        "min_added_vertical_force_g_mm_s2": float(np.min(force)),
        "max_added_vertical_force_g_mm_s2": float(np.max(force)),
        "mean_support_accel_mm_s2": mean_support,
        "support_ratio_to_weight": mean_support / SOURCE_GRAVITY_MM_S2,
        "mean_passive_root_z_no_wing_fluid": float(np.mean(off_passive)),
        "mean_passive_root_z_with_wing_fluid": float(np.mean(on_passive)),
    }


def main() -> int:
    args = parse_args()
    if not args.pattern.exists():
        raise SystemExit(
            f"measured wing pattern missing: {args.pattern}; run "
            "uv run python scripts/dev/prefetch_flybody_flight_data.py"
        )
    if args.phase_samples < 100:
        raise SystemExit("phase-samples must be >= 100")

    cycle = MeasuredWingbeatCycle(args.pattern)
    rows: list[dict[str, object]] = []
    for root_pitch in args.root_pitches_deg:
        for leg_pose in args.leg_poses:
            row = run_case(
                cycle,
                root_pitch_deg=float(root_pitch),
                leg_pose=leg_pose,
                phase_samples=args.phase_samples,
            )
            rows.append(row)
            print(
                "kinematic_aero root_pitch={:.1f} leg_pose={} support_ratio={:.3f} "
                "support_accel={:+.1f} force_mean={:+.6f}".format(
                    float(row["root_pitch_deg"]),
                    row["leg_pose"],
                    float(row["support_ratio_to_weight"]),
                    float(row["mean_support_accel_mm_s2"]),
                    float(row["mean_added_vertical_force_g_mm_s2"]),
                )
            )

    best = max(rows, key=lambda row: float(row["support_ratio_to_weight"]))
    ratio = float(best["support_ratio_to_weight"])
    if ratio < 0.70:
        diagnosis = "EXACT_KINEMATICS_AERODYNAMIC_PORT_UNDERPRODUCES_LIFT"
    elif ratio > 1.30:
        diagnosis = "EXACT_KINEMATICS_AERODYNAMIC_PORT_OVERPRODUCES_LIFT"
    else:
        diagnosis = "EXACT_KINEMATICS_AERODYNAMIC_SUPPORT_APPROXIMATELY_CONSISTENT"

    result = {
        "schema_version": 1,
        "pattern": str(args.pattern),
        "published_flybody_mass_mg": PUBLISHED_FLYBODY_MASS_MG,
        "source_gravity_mm_s2": SOURCE_GRAVITY_MM_S2,
        "cases": rows,
        "diagnosis": diagnosis,
        "interpretation": (
            "Wing qpos/qvel are imposed exactly from the official measured cycle; "
            "actuator and wing-inertia tracking are bypassed. The aero-on minus "
            "aero-off free-root vertical qfrc_passive difference isolates restored "
            "wing-fluid support at identical kinematics."
        ),
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(f"diagnosis={diagnosis}")
    print(f"result={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
