#!/usr/bin/env python3
"""Contrast PAM01 and PPL101 plasticity at a real Flyppy event boundary.

The probe is observational. It first runs one closed-loop Flyppy trajectory from a
fixed condition using the production MaleCNS checkpoint and plasticity semantics,
but without committing the episode-local transaction. The real R1-R6 sensory
current sequence generated by that moving body is recorded until the first gate
pass, collision, finish, or a fixed step limit.

That exact sensory sequence is then replayed into three independent CNS slots:

- control: no DAN stimulation during the final reinforcement steps
- reward: reward_dan / PAM01
- aversive: aversive_dan / PPL101

No slot is committed and no checkpoint is written. The Rust runtime compares the
three episode-local plasticity transactions directly, so the repository does not
accumulate large temporary checkpoint files.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
EMBODIMENT = ROOT / "scripts" / "embodiment"
if str(EMBODIMENT) not in sys.path:
    sys.path.insert(0, str(EMBODIMENT))

from flyppy_packed_body_worker import spawn_packed_body_processes  # noqa: E402
from population_neural_bridge_client import PopulationNeuralBridgeClient  # noqa: E402
from virtual_fly.training.fixed_evaluation import FIXED_EVAL_SUITE_V1  # noqa: E402
from virtual_fly.training.reinforcement_contrast import (  # noqa: E402
    comparison_from_transaction_contrast,
    render_markdown,
)


DEFAULT_PRODUCTION = Path("artifacts/experiments/flyppy-v3")
DEFAULT_SNAPSHOT = Path("artifacts/malecns-v1.0")
DEFAULT_CALIBRATION = Path("artifacts/embodiment/neural-runtime-calibration-v1.json")
DEFAULT_JSON = Path("reports/flyppy/diagnostics/reinforcement_contrast.json")
DEFAULT_REPORT = Path("reports/flyppy/diagnostics/reinforcement_contrast.md")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--production", type=Path, default=DEFAULT_PRODUCTION)
    parser.add_argument("--snapshot", type=Path, default=DEFAULT_SNAPSHOT)
    parser.add_argument("--calibration", type=Path, default=DEFAULT_CALIBRATION)
    parser.add_argument("--condition", default="midpoint")
    parser.add_argument("--course-seed", type=int, default=0)
    parser.add_argument("--trajectory-max-steps", type=int, default=180)
    parser.add_argument("--reinforcement-steps", type=int, default=4)
    parser.add_argument("--reward-current", type=float, default=2.0)
    parser.add_argument("--aversive-current", type=float, default=2.0)
    parser.add_argument("--epsilon", type=float, default=1e-7)
    parser.add_argument("--output-json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    return parser.parse_args()


def absolute(path: Path) -> Path:
    return path if path.is_absolute() else (ROOT / path).resolve()


def portable(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def fixed_condition(name: str):
    for condition in FIXED_EVAL_SUITE_V1:
        if condition.name == name:
            return condition
    available = ", ".join(condition.name for condition in FIXED_EVAL_SUITE_V1)
    raise SystemExit(f"unknown --condition {name!r}; choose one of: {available}")


def capture_closed_loop_history(
    *,
    brain: PopulationNeuralBridgeClient,
    condition,
    snapshot: Path,
    global_weight_version: int,
    course_seed: int,
    max_steps: int,
) -> tuple[list[list[list[float]]], dict[str, object]]:
    workers, _ = spawn_packed_body_processes(
        population=1,
        process_count=1,
        physics_steps=10,
        timeout_s=120.0,
        config={
            "seed": course_seed,
            "gate_count": 6,
            "wing_motor_map": str(snapshot / "wing-motor-neurons-v0.json"),
            "body_motor_map": str(snapshot / "body-motor-neurons-v0.json"),
            "retinotopic_map": str(snapshot / "retinotopic-vision-v1.json"),
            "photoreceptor_current_gain": 2.0,
        },
    )
    worker = workers[0]
    try:
        version = brain.restart_slot(0)
        if version != global_weight_version:
            raise RuntimeError(
                f"driver slot restarted at global version {version}, expected {global_weight_version}"
            )
        worker.request(
            "reset",
            {
                0: {
                    "episode": -1,
                    "source_weight_version": global_weight_version,
                    "spawn_x_mm": condition.x_mm,
                    "spawn_z_mm": condition.z_mm,
                    "initial_speed_mm_s": condition.speed_mm_s,
                }
            },
        )
        worker.receive("reset")

        history: list[list[list[float]]] = []
        terminal: dict[str, object] = {
            "reason": "step_limit",
            "control_steps": 0,
            "passed_gate": False,
            "collision": False,
            "finished": False,
        }
        for control_step in range(max_steps):
            worker.request("observe", (0,))
            observation = dict(worker.receive("observe"))[0]
            body_currents = [
                [int(body_id), float(current)]
                for body_id, current in observation["body_currents"]
            ]
            history.append(body_currents)

            readout = brain.step_batch(
                [
                    {
                        "slot": 0,
                        "stimulate_body": body_currents,
                        "read_body": worker.body_ids[0],
                    }
                ],
                plasticity=True,
            ).get(0, {})
            active_ids = tuple(
                int(body_id) for body_id, fired in readout.items() if bool(fired)
            )
            worker.request("act", {0: active_ids})
            act = dict(worker.receive("act"))[0]

            event = bool(act["passed_gate"]) or bool(act["collision"]) or bool(act["finished"])
            if event:
                terminal = {
                    "reason": (
                        "gate_pass"
                        if bool(act["passed_gate"])
                        else "collision"
                        if bool(act["collision"])
                        else "finished"
                    ),
                    "control_steps": control_step + 1,
                    "passed_gate": bool(act["passed_gate"]),
                    "collision": bool(act["collision"]),
                    "collision_reason": act.get("collision_reason"),
                    "finished": bool(act["finished"]),
                    "position": [float(value) for value in act["position"]],
                    "velocity": [float(value) for value in act["velocity"]],
                    "next_gate": int(act["next_gate"]),
                }
                break
        else:
            terminal["control_steps"] = max_steps

        return history, terminal
    finally:
        for item in workers:
            item.close()


def replay_and_contrast(
    *,
    brain: PopulationNeuralBridgeClient,
    history: list[list[list[float]]],
    global_weight_version: int,
    reward_current: float,
    aversive_current: float,
    reinforcement_steps: int,
    epsilon: float,
) -> tuple[dict[str, object], dict[str, object]]:
    slots = (1, 2, 3)
    for slot in slots:
        version = brain.restart_slot(slot)
        if version != global_weight_version:
            raise RuntimeError(
                f"contrast slot {slot} restarted at global version {version}, expected {global_weight_version}"
            )

    for body_currents in history:
        brain.step_batch(
            [
                {"slot": slot, "stimulate_body": body_currents}
                for slot in slots
            ],
            plasticity=True,
        )

    before = {
        name: brain.transaction_stats(slot)
        for slot, name in zip(slots, ("control", "reward", "aversive"), strict=True)
    }

    for _ in range(reinforcement_steps):
        brain.step_batch(
            [
                {"slot": 1},
                {"slot": 2, "stimulate": {"reward_dan": reward_current}},
                {"slot": 3, "stimulate": {"aversive_dan": aversive_current}},
            ],
            plasticity=True,
        )

    after = {
        name: brain.transaction_stats(slot)
        for slot, name in zip(slots, ("control", "reward", "aversive"), strict=True)
    }
    raw_contrast = brain.transaction_contrast(
        control_slot=1,
        reward_slot=2,
        aversive_slot=3,
        epsilon=epsilon,
    )
    metadata: dict[str, object] = {
        "transaction_before": before,
        "transaction_after": after,
        "raw_transaction_contrast": raw_contrast,
    }
    return comparison_from_transaction_contrast(raw_contrast), metadata


def main() -> int:
    args = parse_args()
    if args.trajectory_max_steps < 1:
        raise SystemExit("--trajectory-max-steps must be >= 1")
    if args.reinforcement_steps < 1 or args.reinforcement_steps % 2 != 0:
        raise SystemExit("--reinforcement-steps must be positive and even")
    if min(args.reward_current, args.aversive_current, args.epsilon) <= 0.0:
        raise SystemExit("currents and epsilon must be positive")

    production = absolute(args.production)
    snapshot = absolute(args.snapshot)
    calibration = absolute(args.calibration)
    checkpoint = production / "checkpoint"
    groups = snapshot / "embodiment-groups-v0.json"
    required = [
        checkpoint / "manifest.json",
        production / "population-state.json",
        groups,
        calibration,
    ]
    missing = [str(path) for path in required if not path.exists()]
    if missing:
        raise SystemExit("missing reinforcement-contrast inputs:\n  " + "\n  ".join(missing))

    condition = fixed_condition(args.condition)
    population_state = load_json(production / "population-state.json")
    global_weight_version = int(population_state["global_weight_version"])
    calibration_payload = load_json(calibration)
    os.environ["VF_NEURAL_SYNAPSE_SCALE"] = str(float(calibration_payload["synapse_scale"]))
    os.environ["VF_FLYPPY_VISION_MODE"] = "direct-ray"
    os.environ["VF_FLYPPY_OMMATIDIA_RAYS"] = "13"
    os.environ.pop("VF_COURSE_START_GATE", None)

    with PopulationNeuralBridgeClient(
        snapshot=snapshot,
        groups=groups,
        slots=4,
        repo_root=ROOT,
    ) as brain:
        loaded = brain.load_checkpoint(
            checkpoint,
            global_weight_version=global_weight_version,
        )
        history, event = capture_closed_loop_history(
            brain=brain,
            condition=condition,
            snapshot=snapshot,
            global_weight_version=global_weight_version,
            course_seed=args.course_seed,
            max_steps=args.trajectory_max_steps,
        )
        comparison, metadata = replay_and_contrast(
            brain=brain,
            history=history,
            global_weight_version=global_weight_version,
            reward_current=args.reward_current,
            aversive_current=args.aversive_current,
            reinforcement_steps=args.reinforcement_steps,
            epsilon=args.epsilon,
        )

    payload: dict[str, object] = {
        "schema_version": 3,
        "checkpoint": portable(checkpoint),
        "checkpoint_step": int(loaded.get("step", -1)),
        "global_weight_version": global_weight_version,
        "condition": condition.name,
        "condition_values": {
            "x_mm": condition.x_mm,
            "z_mm": condition.z_mm,
            "speed_mm_s": condition.speed_mm_s,
        },
        "course_seed": args.course_seed,
        "trajectory_max_steps": args.trajectory_max_steps,
        "trajectory_event": event,
        "sensory_frames": len(history),
        "reinforcement_steps": args.reinforcement_steps,
        "reward_current": args.reward_current,
        "aversive_current": args.aversive_current,
        "epsilon": args.epsilon,
        "arm_metadata": metadata,
        "comparison": comparison,
    }

    output_json = absolute(args.output_json)
    report = absolute(args.report)
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(render_markdown(payload), encoding="utf-8")

    reward = dict(comparison["reward"])
    aversive = dict(comparison["aversive"])
    print(f"trajectory_event={event['reason']}")
    print(f"sensory_frames={len(history)}")
    print(f"reward_changed_edges={reward['changed_edges']}")
    print(f"aversive_changed_edges={aversive['changed_edges']}")
    print(f"shared_changed_edges={comparison['shared_changed_edges']}")
    print(f"changed_jaccard={float(comparison['changed_jaccard']):.6f}")
    print(f"same_sign_fraction={float(comparison['shared_same_sign_fraction']):.6f}")
    print(f"cosine_similarity={float(comparison['cosine_similarity_on_union']):.6f}")
    print(f"report={portable(report)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
